name: æ„å»º Magisk æ¨¡å—

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'ROM ä¸‹è½½é“¾æ¥'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ å…‹éš†ä»“åº“
        uses: actions/checkout@v3

      - name: ğŸ›  å®‰è£…ä¾èµ–
        run: |
          sudo apt update
          sudo apt install -y zip unzip python3-pip
          pip install --user pipx
          pipx ensurepath
          pipx install git+https://github.com/5ec1cff/payload-dumper

      - name: ğŸ§ª æ„å»ºæ¨¡å—
        run: |
          bash ./build.sh "${{ github.event.inputs.url }}"

      - name: ğŸ“¦ ä¸Šä¼ æ„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.version }}
          path: tmp/release/
